Vagrant.configure("2") do |config|
config.vm.box = "bertvv/centos72"
  config.vm.provider "virtualbox" do |vb|
  vb.gui = true
  config.vm.synced_folder "/DevOps", "/vagrant"
  config.vm.provision "shell", path: "config_all.sh"
  end
  
  # Config Server1
	config.vm.define "server1" do |server1|
	server1.vm.hostname = "server1"
	server1.vm.network "private_network", ip: "172.16.0.2"
	server1.vm.network "forwarded_port", guest: "5601", host: "5601"
	server1.vm.network "forwarded_port", guest: "3000", host: "30000"
	#server1.vm.provision "shell", path: "config_server.sh"
	server1.vm.provision "shell",
		inline: "sudo echo '172.16.0.3 node1 node1' >> /etc/hosts"
	
	end
	
  # Config Node1
	config.vm.define "node1" do |node1|
	node1.vm.hostname = "node1"
	node1.vm.network "private_network", ip: "172.16.0.3"
	node1.vm.provision "shell",
		inline: "sudo echo '172.16.0.2 server1 server1' >> /etc/hosts"
	end
  
end
